export * from './entities'
export * from './alpha-model'
export * from './beta-model'
export * from './user.entity'
export * from './casez.entity'
export * from './news.entity'
export * from './book.entity'
export * from './city.entity'
export * from './court.entity'
export * from './specialization.entity'
export * from './lawyer.entity'
export * from './lawyer-team.entity'

